# Release Configuration for UnifiedHQ
# This file configures the automated release management system

# Version Management
versioning:
  strategy: semantic # semantic, calendar, or custom
  auto_bump: true
  bump_files:
    - package.json
    - README.md

# Release Notes Generation
changelog:
  file: CHANGELOG.md
  format: keep-a-changelog # keep-a-changelog, conventional, or custom
  sections:
    - title: '⚠️ Breaking Changes'
      labels: ['breaking-change', 'breaking']
    - title: '✨ New Features'
      labels: ['feature', 'enhancement']
    - title: '🐛 Bug Fixes'
      labels: ['bug', 'fix']
    - title: '🔧 Refactoring'
      labels: ['refactor', 'cleanup']
    - title: '📚 Documentation'
      labels: ['documentation', 'docs']
    - title: '🔄 Other Changes'
      labels: ['chore', 'maintenance']

# Release Notes
release_notes:
  file: RELEASE_NOTES.md
  template: |
    # Release v{version} - {date}

    {changelog_entry}

    ## Installation

    ```bash
    # Using Bun (recommended)
    bun install
    bun run build
    bun start

    # Using Docker
    docker pull ghcr.io/{repository}:{version}
    docker run -p 3000:3000 ghcr.io/{repository}:{version}
    ```

    ## Upgrade Instructions

    1. Pull the latest changes: `git pull origin main`
    2. Install dependencies: `bun install`
    3. Run database migrations: `bunx prisma migrate deploy`
    4. Build the application: `bun run build`
    5. Restart the application: `bun start`

    ## Rollback Instructions

    If you need to rollback to the previous version:

    1. Checkout the previous tag: `git checkout v{previous_version}`
    2. Install dependencies: `bun install`
    3. Run database migrations: `bunx prisma migrate deploy`
    4. Build and restart: `bun run build && bun start`

    ## What's Changed

    {detailed_changes}

    ## Support

    - 📖 [Documentation](https://github.com/{repository}/tree/main/docs)
    - 🐛 [Report Issues](https://github.com/{repository}/issues)
    - 💬 [Discussions](https://github.com/{repository}/discussions)

# Branch Strategy
branches:
  main: main
  develop: develop
  release_prefix: release/
  hotfix_prefix: hotfix/

# Environments
environments:
  staging:
    branch: develop
    auto_deploy: true
    url: https://staging.unifiedhq.com
  production:
    branch: main
    auto_deploy: false # Requires manual approval
    url: https://unifiedhq.com

# Artifacts
artifacts:
  build_dir: .next
  include:
    - .next/
    - public/
    - package.json
    - bun.lock
    - next.config.mjs
    - tailwind.config.ts
    - tsconfig.json
    - prisma/
    - src/generated/
  exclude:
    - node_modules/
    - .git/
    - .env*
    - '*.log'

# Docker Configuration
docker:
  registry: ghcr.io
  image_name: unifiedhq
  platforms:
    - linux/amd64
    - linux/arm64
  tags:
    - latest
    - '{version}'
    - '{major}.{minor}'
    - '{major}'

# Notifications
notifications:
  slack:
    enabled: true
    webhook_var: SLACK_WEBHOOK_URL
    channels:
      - '#releases'
      - '#general'
  email:
    enabled: false
    recipients: []

# Security
security:
  sign_releases: true
  verify_checksums: true
  scan_vulnerabilities: true

# Quality Gates
quality_gates:
  pre_release:
    - lint
    - test
    - build
    - security_scan
  post_release:
    - health_check
    - smoke_test
    - performance_check

# Rollback Configuration
rollback:
  auto_rollback: false
  health_check_timeout: 300 # seconds
  rollback_on_failure: true
  preserve_data: true

# Monitoring
monitoring:
  health_check_url: '/api/health'
  performance_threshold: 2000 # ms
  error_rate_threshold: 0.01 # 1%
  uptime_threshold: 0.99 # 99%
