version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "jest",
    "jquery",
    "cypress"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"